version: '3.9'

services:
  db:
    image: postgres:15
    container_name: aiogram_postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./src/.env
    networks:
      - aiogram

  app:
    build:
      context: .
    image: aiogram
    container_name: aiogram_app
    command: ["/aiogram/scripts/entrypoint.sh"]
    env_file:
      - ./src/.env
    volumes:
      - .:/aiogram
    networks:
      - aiogram
    
    depends_on:
      - db
      - redis

  pgadmin:
    container_name: aiogram_pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    restart: on-failure
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - aiogram

  redis:
    image: redis:latest
    container_name: aiogram_redis
    ports:
      - "6378:6379"
    networks:
      - aiogram

  celery:
    build:
        context: .
    command: sh -c "cd src && celery -A celery_app:celery worker --loglevel=INFO"
    env_file:
      - ./src/.env
    volumes:
      - .:/aiogram
    container_name: aiogram_celery
    depends_on:
      - redis
    networks:
      - aiogram

networks:
  aiogram:

volumes:
  postgres-data: