"""init

Revision ID: 6fa71d6c29d8
Revises: 
Create Date: 2023-08-07 14:48:52.494401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fa71d6c29d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('username', sa.String(), nullable=False),
                    sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
                    sa.PrimaryKeyConstraint('username'),
                    sa.UniqueConstraint('username')
                    )
    op.create_table('categories',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('accounting',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('user_id', sa.String(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.Column('categories', sa.UUID(), nullable=True),
                    sa.ForeignKeyConstraint(['categories'], ['categories.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.username'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounting')
    op.drop_table('categories')
    op.drop_table('user')
    # ### end Alembic commands ###
