"""is_active field

Revision ID: 8ca044247220
Revises: 9594cf3d5f56
Create Date: 2023-08-10 22:05:15.380398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ca044247220'
down_revision = '9594cf3d5f56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'is_active')
    # ### end Alembic commands ###
