"""locale field

Revision ID: 9594cf3d5f56
Revises: 7ab38ff3ef21
Create Date: 2023-08-10 12:16:23.991396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9594cf3d5f56'
down_revision = '7ab38ff3ef21'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('locale', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'locale')
    # ### end Alembic commands ###
